In [1]:
import pandas as pd
import numpy as np

# Load in and characterize the two datasets
I did not explore / characterize these datasets as much as I would have liked.

I gained some insight into the column headers [**here**](https://www.milliman.com/en/insight/price-transparency-provider-network-identification). Most importantly, I learned what plan name specifically refers to (in conjunction with a payer name) and figured that product types (PPO, HMO, etc.) could be relevant here.

In [8]:
# Import payer dataset
payer_df = pd.read_csv('./payer_extract_20250203.csv')

In [3]:
# Characterize payer dataset
print('=== (rows, columns):', payer_df.shape, '\n')
print('=== missingness per field:')
print(payer_df.isna().sum(), '\n')
print('=== data type per field:')
print(payer_df.dtypes,'\n')
print('=== table head:')
payer_df.head()

=== (rows, columns): (2950, 22) 

=== missingness per field:
source_file_name                            0
hospital_id                                 0
hospital_name                               0
last_updated_on                             0
hospital_state                              0
license_number                              0
payer_name                                  0
plan_name                                   0
code_type                                   0
raw_code                                    0
description                                 0
setting                                     0
modifiers                                2916
standard_charge_gross                     943
standard_charge_discounted_cash           930
standard_charge_negotiated_dollar         426
standard_charge_negotiated_percentage    2280
standard_charge_min                      2322
standard_charge_max                      2322
standard_charge_methodology               214
additional_payer_no

source_file_name  \
0  13-1740114_montefiore-medical-center_standardc...   
1  13-1740114_montefiore-medical-center_standardc...   
2  13-1740114_montefiore-medical-center_standardc...   
3  13-1740114_montefiore-medical-center_standardc...   
4  13-1740114_montefiore-medical-center_standardc...   

                            hospital_id              hospital_name  \
0  62915ae8-8d64-4e2f-b05f-b18edde57a3d  Montefiore Medical Center   
1  62915ae8-8d64-4e2f-b05f-b18edde57a3d  Montefiore Medical Center   
2  62915ae8-8d64-4e2f-b05f-b18edde57a3d  Montefiore Medical Center   
3  62915ae8-8d64-4e2f-b05f-b18edde57a3d  Montefiore Medical Center   
4  62915ae8-8d64-4e2f-b05f-b18edde57a3d  Montefiore Medical Center   

  last_updated_on hospital_state license_number   payer_name  \
0      2024-07-01             NY     13-1740114        Aetna   
1      2024-07-01             NY     13-1740114  HealthFirst   
2      2024-07-01             NY     13-1740114        Aetna   
3      2024-07-01             NY     13-1740114        Cigna   
4      2024-07-01             NY     13-1740114        Oscar   

              plan_name code_type raw_code  ... modifiers  \
0              Medicare       CPT    99283  ...       NaN   
1  Commercial Enrollees       CPT    43239  ...       NaN   
2            Commercial       CPT    43239  ...       NaN   
3             LocalPlus       CPT    99283  ...       NaN   
4              Medicare       CPT    43239  ...       NaN   

  standard_charge_gross standard_charge_discounted_cash  \
0                   NaN                             NaN   
1                   NaN                             NaN   
2                   NaN                             NaN   
3                3744.0                          2433.6   
4                   NaN                             NaN   

   standard_charge_negotiated_dollar  standard_charge_negotiated_percentage  \
0                             323.34                                    NaN   
1                            1037.65                                    NaN   
2                            1246.73                                    NaN   
3                            1797.00                                    NaN   
4                            1037.65                                    NaN   

   standard_charge_min  standard_charge_max  standard_charge_methodology  \
0                83.78              1009.22                 fee schedule   
1               165.40              3206.34                 fee schedule   
2              1246.73              1394.79                 fee schedule   
3               225.00              1797.00                        other   
4               141.77              1815.10                 fee schedule   

   additional_payer_notes additional_generic_notes  
0                     NaN                      NaN  
1                     NaN                      NaN  
2                     NaN                      NaN  
3                     NaN                per visit  
4                     NaN                      NaN  

[5 rows x 22 columns]

In [4]:
# Import hospital dataset
hospital_df = pd.read_csv('./hospital_extract_20250203.csv')

In [5]:
print('=== (rows, columns):', hospital_df.shape, '\n')
print('=== missingness per field:')
print(hospital_df.isna().sum(), '\n')
print('=== data type per field:')
print(hospital_df.dtypes,'\n')
print('=== table head:')
hospital_df.head()

=== (rows, columns): (222, 17) 

=== missingness per field:
payer                           0
network_name                    0
network_id                      0
network_year_month              0
network_region                  0
code                            0
code_type                       0
ein                             0
taxonomy_filtered_npi_list      4
modifier_list                 215
billing_class                   0
place_of_service_list          25
negotiation_type                0
arrangement                     0
rate                            0
cms_baseline_schedule           1
cms_baseline_rate               1
dtype: int64 

=== data type per field:
payer                          object
network_name                   object
network_id                     object
network_year_month              int64
network_region                 object
code                            int64
code_type                      object
ein                             int64
taxonomy_filtered_

payer network_name                            network_id  \
0  unitedhealthcare  choice-plus  592bc118-0dac-4f38-949c-11dc9b3a3879   
1  unitedhealthcare  choice-plus  592bc118-0dac-4f38-949c-11dc9b3a3879   
2  unitedhealthcare  choice-plus  592bc118-0dac-4f38-949c-11dc9b3a3879   
3  unitedhealthcare  choice-plus  592bc118-0dac-4f38-949c-11dc9b3a3879   
4  unitedhealthcare  choice-plus  592bc118-0dac-4f38-949c-11dc9b3a3879   

   network_year_month network_region   code code_type        ein  \
0              202501            USA    872    MS-DRG  131740114   
1              202501            USA  99283       CPT  131624096   
2              202501            USA  43239       CPT  131740114   
3              202501            USA    872    MS-DRG  133971298   
4              202501            USA  43239       CPT  131740114   

                          taxonomy_filtered_npi_list modifier_list  \
0  1003990763,1023202793,1063525152,1063606739,10...           NaN   
1  1003255670,1245759711,1487026522,1598095267,16...           NaN   
2        1700348620,1700892056,1922539964,1942685292           NaN   
3  1245635200,1437523537,1528013695,1528432622,15...           NaN   
4                                         1346697315           NaN   

   billing_class place_of_service_list negotiation_type arrangement      rate  \
0  institutional                   NaN       negotiated         ffs  15902.00   
1   professional                    11       negotiated         ffs    123.86   
2   professional                    11       negotiated         ffs    993.92   
3  institutional                   NaN       negotiated         ffs  27924.63   
4   professional                    11       negotiated         ffs    849.63   

     cms_baseline_schedule  cms_baseline_rate  
0                     IPPS            6829.75  
1  PFS_NONFACILITY_1320201              76.89  
2  PFS_NONFACILITY_1320202             424.76  
3                     IPPS            6829.75  
4  PFS_NONFACILITY_1320203             391.85

# Figure out how to match a row in the hospital dataset to a row in the payer dataset
Ideally, this is a one-to-one match, but may be imperfect. I realized that EIDs correspond to license numbers (each hospital or system seems to have an EID and a license number that correspond somewhat one to one, at least for the purposes of this exercise).

In [6]:
# Identify unique EINs in the hospital data; these are essentially hospital IDs
hospital_df.ein.value_counts()

ein
131740114    118
133971298     55
131624096     49
Name: count, dtype: int64

In [7]:
# Identify unique license_numbers in the payer data; these correspond to the hospital IDs in some way
payer_df.license_number.value_counts()

license_number
7002053H      2322
13-1740114     380
330024         248
Name: count, dtype: int64

Ideally, we would have a table of corresponding EINs, license numbers, and hospital names to cross-reference, which is vital for this type of dataset joining at scale.

For now, let's assume we have that table, which would give us the following:
- Montefiore has EIN 131740114 and license_number 13-1740114
- NYU Langone has EIN 133971298 and license_number 7002053H
- Mount Sinai Hospital has EIN 131624096 and license_number 330024

# Figure out how to match a payer & plan in the hospital dataset to a payer & plan in the payer dataset

In [10]:
# Now, identify unique payer + network_name pairs in the hospital dataset
(hospital_df.payer + ': ' + hospital_df.network_name).value_counts()

aetna: open-access-managed-choice    133
unitedhealthcare: choice-plus         45
cigna-corporation: national-oap       44
Name: count, dtype: int64

Preliminary research showed that all 3 of these are commercial, PPO-style plans.

In [11]:
# Identify all Aetna plans in payer data
payer_df[payer_df.payer_name.str.contains('aetna',case=False)].plan_name.value_counts()

plan_name
Medicare                                     12
Commercial                                    8
nipponlife-aetna1394                          6
aetnasignatureadministratorsppo1417           6
christianbrothers1640                         6
coresource1642                                6
aetnastudentplan1008                          6
chesterfieldresourcesinc1641                  6
aetnaopenaccesshmo1414                        6
wellnet1755                                   6
aetnameritainhealth1444                       6
aetnaopenaccesselectchoice(epo)1415           6
allied3025                                    6
aetnaindemnity1006                            6
starmark1643                                  6
aetnappo1010                                  6
healthscope3250                               6
aetnahmo1005                                  6
aetnapos1009                                  6
geha1067                                      6
aetnaglobalnationaltransplant(

In [12]:
# Identify all United Healthcare plans in payer data
payer_df[(payer_df.payer_name.str.contains('united',case=False))|
         (payer_df.payer_name.str.contains('uhc',case=False))].plan_name.value_counts()

plan_name
unitedhealthcarestudentresources1405                     6
unitedhealthcarehmo1156                                  6
oxfordgardenstate3102                                    6
unitedhealthcarechoice(paramountemployees)3665           6
unitedhealthcarechoicenslij1773                          6
unitedhealthcareinde1157                                 6
unitedhealthcarechoice1291                               6
unitedhealthcarenavigate1404                             6
unitedhealthcarepos1159                                  6
unitedhealthcareppo1160                                  6
unitedhealthcareepo1155                                  6
umr1323                                                  6
Medicare Advantage, Community Plan Medicare Advantage    6
nyshealthinsuranceplannyshipalt3768                      5
All Payers                                               4
goldenruleinsurance3914                                  4
unitedhealthcareoptumhealth1352               

In [13]:
# Identify all Cigna plans in payer data
payer_df[payer_df.payer_name.str.contains('cigna',case=False)].plan_name.value_counts()

plan_name
LocalPlus                             6
cignaopenaccessppo1465                6
cignaindemnity1045                    6
tuftshealthplan3661                   6
cignagreatwestppo1442                 6
consolidatedhealthplan(hbonly)1367    6
cignamanagedcare/pos1046              6
cignanalc1448                         6
wellfleet-nyustudent3059              6
cignapremierplus1048                  6
cignaopenaccesshmo(hbonly)1466        6
greatwesthmo1282                      6
cignahmo1403                          6
cignaevernorthbehavioralhealth1490    6
mvp-cignanetwork1331                  6
cignalifesource(hbonly)1678           6
cignaopenaccess1413                   6
cignappo1047                          6
Lifesource                            3
HMO and PPO                           2
Name: count, dtype: int64

There are 2 Aetna plans with "open access" in their name, but they're not quite matched with "open-access-managed-choice". Therefore, we can consider both. There are also some more generic "plan names" that seem to work, including "Commercial", "aetnappo1010", and "HMO/POS/PPO".

There are 2 UHC plans with "choice" in their name, but they're not quite matched with "choice-plus". Therefore, we can consider both. There are again some more generic "plan names" that seem to work, including "unitedhealthcareppo1160" and "All Payer".

There are 3 Cigna plans with "open access" (OAP = open access plan), and "cignaopenaccess1413" and "cignaopenaccessppo1465" are the best matches. Therefore, we can consider both. There are yet again some more generic "plan names" that seem to work, including "cignappo1047" and "HMO and PPO".

# Decisions made for matching
In the hospital dataset, we have 3 plans:
1. Aetna Open Access Managed Choice
2. United Healthcare Choice Plus
3. Cigna Corporation National OAP

To attempt a match of payer & plan between a hospital dataset row and a payer dataset row, I first check for matching payer names. For Aetna and Cigna, this is just a case-insensitive match of 'Aetna' and 'Cigna' in the payer dataset. However, for United Healthcare this involves checking for both 'United' and 'UHC', since both are used in the payer dataset.

Next, ideally we would have a perfect plan name (or unique plan identifier) match between the two datasets. However, that is simply not the case, and has varying levels of success depending on the hospital and payer/plan. Additionally, we want to match the code type and number, and ideally we want to get the best match between negotiation_type in the hospital dataset and the combination of standard_charge_methodology and additional_generic_notes in the payer dataset.

I decided to consider classifying each of the three plans of interest somewhat categorically, since plan name matches are inexact, but plan types might match sufficiently. As mentioned earlier, all three plans seem to fall under the PPO umbrella, with the Cigna plan possible also including HMO. Therefore, for all three plans, I thought I would try to match plan name based on what I see or go with category if the option was available. If both category and plan name seemed to work, then there would be several options to consider.

The best solution I identified for right now, given time constraints: Create a list of acceptable plan names from the payer dataset, and match payer_name exactly (as described above) and then a plan name from the list. This list essentially includes the closest plan names and/or general labels that encompass PPO in some way (PPO, or commercial, or all plans). For payer dataset rows not matched with a hospital dataset row (i.e., not in the good_plan_names list), I will still include them in the output dataset, but noting clearly the lack of match.

As mentioned above, CPT code matching is easy, but ultimately we also need to match negotiation_type (in the payer dataset) to the combination of standard_charge_methodology and additional_generic_notes (in the hospital dataset).

In [14]:
# Unique plan names across all 3 payers
payer_df[(payer_df.payer_name.str.contains('cigna', case=False))|(payer_df.payer_name.str.contains('aetna', case=False))|
         (payer_df.payer_name.str.contains('united', case=False))|(payer_df.payer_name.str.contains('uhc', case=False))].plan_name.unique().tolist()

['Medicare',
 'Commercial',
 'LocalPlus',
 'HC NY Essential',
 'ASA',
 'All Payers',
 'Medicare Advantage',
 'HC Oxford',
 'Empire Plan',
 'Medicare Advantage, Community Plan Medicare Advantage',
 'HMO and PPO',
 'Blackstone, Student Health, Savings Plus',
 'HMO/POS/PPO',
 'cignappo1047',
 'umr1323',
 'unitedhealthcareepo1155',
 'geha1067',
 'unitedhealthcareppo1160',
 'cignaopenaccess1413',
 'aetnapos1009',
 'aetnahmo1005',
 'cignalifesource(hbonly)1678',
 'healthscope3250',
 'unitedhealthcarehmo1156',
 'unitedhealthcarestudentresources1405',
 'aetnappo1010',
 'mvp-cignanetwork1331',
 'unitedhealthcarechoice1291',
 'cignaevernorthbehavioralhealth1490',
 'starmark1643',
 'aetnaindemnity1006',
 'nyshealthinsuranceplannyshipalt3768',
 'goldenruleinsurance3914',
 'allied3025',
 'cignahmo1403',
 'unitedhealthcareinde1157',
 'unitedhealthcarechoicenslij1773',
 'aetnaopenaccesselectchoice(epo)1415',
 'greatwesthmo1282',
 'aetnameritainhealth1444',
 'cignaopenaccesshmo(hbonly)1466',
 'cignapr

In [15]:
# Acceptable plan names, for now
good_plan_names = ['Commercial', 'All Payers', 'HMO and PPO', 'HMO/POS/PPO', 'cignappo1047', 'unitedhealthcareppo1160',
                   'cignaopenaccess1413', 'aetnappo1010', 'cignaopenaccessppo1465', 'aetnaopenaccesshmo1414']
# Dictionary linking each EID (key) to the license number for the same hospital (value)
hospital_matches = {131740114: '13-1740114', 
                    133971298: '7002053H', 
                    131624096: '330024'}
# Create an empty hospital dataset row to append to each payer dataset row without a match
empty_hospital = [None] * hospital_df.shape[1]
# Create an empty payer dataset row to append to each hospital dataset row without a match
empty_payer = [None] * payer_df.shape[1]
# Append "hospitaldf_" to each hospital dataset column header, for clarity
hospital_header = ['hospitaldf_' + str(col) for col in hospital_df.columns]
# Append "payerdf_" to each payer dataset column header, for clarity
payer_header = ['payerdf_' + str(col) for col in payer_df.columns]
# Combine the hospital and payer dataset headers
combined_header = hospital_header + payer_header
# Empty list to store matched rows (or unmatched rows, when such cases appear)
combined_df = []
# Empty list to store payers that have been matched to a hospital dataset row
payer_df_rows_matched = []

for index, row in hospital_df.iterrows():
    curr_payer = row.payer
    curr_ein = row.ein
    curr_license = hospital_matches[curr_ein]
    curr_code_type = row.code_type
    if curr_code_type == 'CPT':      # Convert CPT codes to strings
        curr_code = str(row.code)
    elif curr_code_type == 'MS-DRG': # Append MS-DRG to such codes, to match payer dataest format of these codes
        curr_code = 'MS-DRG '+ str(row.code)
    if curr_payer != 'unitedhealthcare': # Simple match for non-UHC payer
        matched_rows = payer_df[payer_df.payer_name.str.contains(curr_payer, case=False)]
    else: # Extra check for UHC payer
        matched_rows = payer_df[(payer_df.payer_name.str.contains('united', case=False))|
                                (payer_df.payer_name.str.contains('uhc', case=False))]
    matched_rows = matched_rows[matched_rows.license_number == curr_license]
    matched_rows = matched_rows[matched_rows.plan_name.isin(good_plan_names)]
    matched_rows = matched_rows[(matched_rows.code_type==curr_code_type)&(matched_rows.raw_code==curr_code)]
    # If at least one payer dataset row matches a hospital dataset row, combined them
    if matched_rows.shape[0] > 0:
        for payer_index, payer_row in matched_rows.iterrows():
            new_row = row.tolist() + payer_row.tolist()
            combined_df.append(new_row)
            payer_df_rows_matched.append(payer_index)
    # If no match, combine an empty payer row with that hospital dataset row
    else:
        new_row = row.tolist() + empty_payer
        combined_df.append(new_row)
        
payer_df_rows = sorted(list(set(payer_df_rows_matched)))
# If no hospital dataset row matches a payer dataset row, combine an empty hospital row with that payer dataset row
for index, row in payer_df.iterrows():
    if index not in payer_df_rows:
        new_row = empty_hospital + row.tolist()
        combined_df.append(new_row)

In [17]:
# List of lists --> dataframe
combined_df = pd.DataFrame(combined_df, columns=combined_header)
combined_df.head()

hospitaldf_payer hospitaldf_network_name  \
0  unitedhealthcare             choice-plus   
1  unitedhealthcare             choice-plus   
2  unitedhealthcare             choice-plus   
3  unitedhealthcare             choice-plus   
4  unitedhealthcare             choice-plus   

                  hospitaldf_network_id  hospitaldf_network_year_month  \
0  592bc118-0dac-4f38-949c-11dc9b3a3879                       202501.0   
1  592bc118-0dac-4f38-949c-11dc9b3a3879                       202501.0   
2  592bc118-0dac-4f38-949c-11dc9b3a3879                       202501.0   
3  592bc118-0dac-4f38-949c-11dc9b3a3879                       202501.0   
4  592bc118-0dac-4f38-949c-11dc9b3a3879                       202501.0   

  hospitaldf_network_region  hospitaldf_code hospitaldf_code_type  \
0                       USA            872.0               MS-DRG   
1                       USA          99283.0                  CPT   
2                       USA          43239.0                  CPT   
3                       USA          43239.0                  CPT   
4                       USA            872.0               MS-DRG   

   hospitaldf_ein              hospitaldf_taxonomy_filtered_npi_list  \
0     131740114.0  1003990763,1023202793,1063525152,1063606739,10...   
1     131624096.0  1003255670,1245759711,1487026522,1598095267,16...   
2     131740114.0        1700348620,1700892056,1922539964,1942685292   
3     131740114.0        1700348620,1700892056,1922539964,1942685292   
4     133971298.0  1245635200,1437523537,1528013695,1528432622,15...   

  hospitaldf_modifier_list  ... payerdf_modifiers  \
0                      NaN  ...              None   
1                      NaN  ...              None   
2                      NaN  ...               NaN   
3                      NaN  ...               NaN   
4                      NaN  ...               NaN   

  payerdf_standard_charge_gross payerdf_standard_charge_discounted_cash  \
0                           NaN                                     NaN   
1                           NaN                                     NaN   
2                        3925.0                                 2551.25   
3                        1790.0                                 1163.50   
4                           NaN                                     NaN   

  payerdf_standard_charge_negotiated_dollar  \
0                                       NaN   
1                                       NaN   
2                                    688.30   
3                                    688.30   
4                                  34416.84   

   payerdf_standard_charge_negotiated_percentage payerdf_standard_charge_min  \
0                                            NaN                         NaN   
1                                            NaN                         NaN   
2                                            NaN                      146.49   
3                                            NaN                      146.49   
4                                            NaN                         NaN   

   payerdf_standard_charge_max payerdf_standard_charge_methodology  \
0                          NaN                                None   
1                          NaN                                None   
2                      1733.49                        fee schedule   
3                      1733.49                        fee schedule   
4                          NaN                           Case Rate   

                      payerdf_additional_payer_notes  \
0                                               None   
1                                               None   
2                                                NaN   
3                                                NaN   
4  Medicare Base Rate times Standard Inpatient We...   

  payerdf_additional_generic_notes  
0                             None  
1                             None  
2                       

In [18]:
# Unmatched payers from payer_df (retained for completeness)
print(combined_df[combined_df.hospitaldf_payer.isnull()].shape[0], 'unmatched payers from payer_df')

# Unmatched rows from hospital_df (retained for completeness)
print(combined_df[combined_df.payerdf_payer_name.isnull()].shape[0], 'matched hospital_df rows')

# Rows with matching (perhaps duplicated hospital rows, definitely duplicated payer rows)
print(combined_df[(~combined_df.payerdf_payer_name.isnull())&(~combined_df.hospitaldf_payer.isnull())].shape[0], 
      'rows where a hospital_df row matches a payer_df row')

2926 unmatched payers from payer_df
73 matched hospital_df rows
464 rows where a hospital_df row matches a payer_df row


In [19]:
combined_df.to_csv('./20250209_takehome_code_output.csv', index=False)

# That's all I had time for
Here is what I would do after this point:

In addition to matching everything in the hospital dataset with something in the payer dataset, where possible, I need an indication of how good the match is. Important factors and considerations:
- Do the payer and plan names match nearly perfectly?
- Does the payer name match but the plan name only generally match?
- Does the methodology (negotiation, etc.) also match?
- Do the charges match? If there is a discrepancy, why? Does one value trump the other?

Additionally, I would remove all but one of the matches in cases where a hospital dataset row has multiple matched payer dataset rows, but there is a clear "winner" (best match). If there isn't a clear best match, then the multiple matches would need to be integrate somehow, but I do not presently know the best approach for this.